CREATE TABLE assistant_bulk_operations (
    id VARCHAR(36) PRIMARY KEY,
    bulk_execution_id VARCHAR(100) NOT NULL UNIQUE,
    tool_name VARCHAR(120) NOT NULL,
    actor_id VARCHAR(36) NOT NULL,
    scope VARCHAR(32) NOT NULL,
    operation_scope VARCHAR(32) NOT NULL,
    preview_hash VARCHAR(128) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    duplicate_rows INT NOT NULL DEFAULT 0,
    succeeded_rows INT NOT NULL DEFAULT 0,
    failed_rows INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    payload_json LONGTEXT,
    result_json LONGTEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    INDEX idx_bulk_actor (actor_id),
    INDEX idx_bulk_status (status),
    INDEX idx_bulk_created_at (created_at)
);
