spring.application.name=dailymate
server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.error.include-message=never
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
app.security.jwt.secret=${APP_JWT_SECRET:ZmFrZS1zZWNyZXQta2V5ZmFrZS1zZWNyZXQ=}

app.security.jwt.access-token-ttl=PT15M
app.security.jwt.refresh-token-ttl=P7D
